=== IsiSku/XML-BSEP/xml/Propis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/propisi" xmlns:pro="http://www.ftn.uns.ac.rs/propisi">
    <xs:element name="Propis">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="pro:Deo"/>
            </xs:sequence>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="pro:Glava"/>
            </xs:sequence>
            <xs:attribute name="Redni_broj" type="xs:string"/>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glava">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="pro:Odeljak"/>
            </xs:sequence>
            <xs:attribute name="Redni_broj" type="xs:positiveInteger"/>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Pododeljak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="pro:Clan"/>
                        </xs:sequence>
                        <xs:attribute name="Slovo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:length value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="Naziv" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="pro:Clan"/>
            </xs:sequence>
            <xs:attribute name="Redni_broj" type="xs:positiveInteger"/>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="pro:Stav"/>
            </xs:sequence>
            <xs:attribute name="Redni_broj" type="xs:positiveInteger"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stav">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pro:Sadrzaj"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Sadrzaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="pro:Tacka"/>
                <xs:element maxOccurs="unbounded" name="Tekst" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Tacka">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Tekst" type="xs:string"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="Podtacka">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tekst" type="xs:string"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="Alineja"
                                type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="Redni_broj" type="xs:positiveInteger"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="Redni_broj" type="xs:positiveInteger"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IsiSku/XML-BSEP/BackendApp/busepBackend/xml/akt.xml
<?xml version="1.0" encoding="UTF-8"?>
<Propis xmlns="http://www.ftn.uns.ac.rs/propisi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/propisi file:/R:/CETVRTA%20GODINA/XML-BSEP-Projekat/XML-BSEP/xml/Propis.xsd">
    <Deo>
        <Glava>
            <Odeljak>
                <Clan>
                    <Stav>
                        <Tekst>LeSe5</Tekst>
                    </Stav>
                    <Stav>
                        <Tacka>
                            <Tekst>nI7</Tekst>
                        </Tacka>
                        <Tacka>
                            <Podtacka>
                                <Tekst>Z0YgaO6</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>n_x60SwFZ</Alineja>
                                <Alineja>zO</Alineja>
                                <Alineja>RbwU0eutfIU</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>I8gxqEkyYn5JABCSRVjy</Tekst>
                            </Podtacka>
                        </Tacka>
                        <Tacka>
                            <Podtacka>
                                <Tekst>J8qteIjQNpAIvgsf6b9</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>I7PKjbT.HL_o1cxZpGUk2PJxfSNJ</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>RbP17HjNl.xLe_ZQo8</Alineja>
                                <Alineja>CZPD5v8</Alineja>
                                <Alineja>QZ2rZ4pVwgWwBmes8bQw4uCaYY</Alineja>
                            </Podtacka>
                        </Tacka>
                    </Stav>
                    <Stav>
                        <Tekst>XYd48i6_DnZ6.4</Tekst>
                    </Stav>
                </Clan>
                <Clan>
                    <Stav>
                        <Tacka>
                            <Tekst>AAS6H6UlJiq27GCyZmNPSx3A</Tekst>
                        </Tacka>
                        <Tacka>
                            <Tekst>pbETeSaDPsoDzP6qe7oe</Tekst>
                        </Tacka>
                        <Tacka>
                            <Podtacka>
                                <Alineja>tJmPr1RNbW_R</Alineja>
                                <Alineja>wizHkkF</Alineja>
                                <Alineja>U</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>Qq5tjuml</Alineja>
                                <Alineja>r_S3D</Alineja>
                                <Alineja>xeu</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>Kux8o4txm66fCSnIow_vkb</Tekst>
                            </Podtacka>
                        </Tacka>
                    </Stav>
                    <Stav>
                        <Tacka>
                            <Podtacka>
                                <Tekst>ZWuNzCb9ArCyH5Gvol0Z7lgYeTzW6</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>c2MolMw_ERhvv</Alineja>
                                <Alineja>FA20iInChvzTU5MIqMap.aDzDJMk</Alineja>
                                <Alineja>tgnKvKaxUmayBPZ-2bXcI</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>cCjdcVDs7ATFAU2__0MNGqsM</Tekst>
                            </Podtacka>
                        </Tacka>
                        <Tacka>
                            <Tekst>TUtqwQCSzhiUQgDS7ISZzWynKtsNb</Tekst>
                        </Tacka>
                        <Tacka>
                            <Tekst>gVL7zQETUvZGprYjjpbH2yCDinrEw</Tekst>
                        </Tacka>
                    </Stav>
                    <Stav>
                        <Tacka>
                            <Podtacka>
                                <Tekst>GU8CUaOaEGmq8z6G</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>RwM..9.Kt.8Fa</Alineja>
                                <Alineja>VSkwU</Alineja>
                                <Alineja>Dt-a</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>gyANxC2hRYhd</Alineja>
                                <Alineja>DY</Alineja>
                                <Alineja>ihsgHiC.IpU</Alineja>
                            </Podtacka>
                        </Tacka>
                        <Tacka>
                            <Tekst>_x3OIWDOHuhir4pral7S</Tekst>
                        </Tacka>
                        <Tacka>
                            <Tekst>UuBJjYrxdCb.F-</Tekst>
                        </Tacka>
                    </Stav>
                </Clan>
                <Clan>
                    <Stav>
                        <Tacka>
                            <Podtacka>
                                <Alineja>bEROfCp.1O1v</Alineja>
                                <Alineja>MQzr4z4JdXIGogDG_kB</Alineja>
                                <Alineja>_Oq9r9n4</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>ZNDkGHj8sIaV4T</Alineja>
                                <Alineja>IMOwv85x</Alineja>
                                <Alineja>U6-HZ8kfp8Df</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>A</Tekst>
                            </Podtacka>
                        </Tacka>
                        <Tacka>
                            <Tekst>VT_tB</Tekst>
                        </Tacka>
                        <Tacka>
                            <Tekst>tXW.mPDFDplVQPfpJU0h.Rk_</Tekst>
                        </Tacka>
                    </Stav>
                    <Stav>
                        <Tacka>
                            <Tekst>KdB7H</Tekst>
                        </Tacka>
                        <Tacka>
                            <Tekst>lI5wKZL</Tekst>
                        </Tacka>
                        <Tacka>
                            <Tekst>HKZ9hUBJkCsKcRdqX6I</Tekst>
                        </Tacka>
                    </Stav>
                    <Stav>
                        <Tacka>
                            <Podtacka>
                                <Alineja>shifMj5aaJrYv0in6K</Alineja>
                                <Alineja>uyKZMpjZDWM_Hze</Alineja>
                                <Alineja>ifydeXzUaa</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>_ofyWBr6Qrc72</Alineja>
                                <Alineja>AuqtIoi3eMK</Alineja>
                                <Alineja>Byky7mOSeFDf6Qi_BD</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>MVHoVRUm8qrB</Tekst>
                            </Podtacka>
                        </Tacka>
                        <Tacka>
                            <Podtacka>
                                <Alineja>EoqFWO5</Alineja>
                                <Alineja>tXAONZDNqI5kuElup7N8qhZF7y-Y1K</Alineja>
                                <Alineja>zrCqFk077aZzgz0ElZx-IavNhS3iX</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>uL2xRQ38H7nmDdMLHi1gDDpy</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>O_EE</Tekst>
                            </Podtacka>
                        </Tacka>
                        <Tacka>
                            <Podtacka>
                                <Alineja>UL5uon6dA3a3kcp_FcPBx</Alineja>
                                <Alineja>EbLGX</Alineja>
                                <Alineja>tQ6Djo</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>ko_TE7X</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>QYOyOmdZeI1E</Tekst>
                            </Podtacka>
                        </Tacka>
                    </Stav>
                </Clan>
            </Odeljak>
            <Odeljak>
                <Clan>
                    <Stav>
                        <Tekst>oo41dzBWCAKEVcGCA6.Lv</Tekst>
                    </Stav>
                    <Stav>
                        <Tacka>
                            <Tekst>z465VuZp7qnlYlVVgIVI-AiY</Tekst>
                        </Tacka>
                        <Tacka>
                            <Podtacka>
                                <Tekst>APaIsEiUns</Tekst>
                            </Podtacka>
                            <Podtacka>
                                <Alineja>h7T_M._hGaoubTBc3DrJVX3v5Gu5L6</Alineja>
                                <Alineja>a</Alineja>
                                <Alineja>Uwx7Na4po4MfKGEZTX9ud_</Alineja>
                            </Podtacka>
                            <Podtacka>
                                <Tekst>XSi3WVgnB_UDv___4l8TW7kygit</Tekst>
                            </Podtacka>
                        </Tacka>
                        <Tacka>
                            <Podtacka>
